In [1]:
import numpy as np

# 1. Array operations

## Arithmetic operations

In [2]:
a1 = np.array([1,2,3,4,5]) 
a2 = np.array([6,7,8,9,10])
a1


array([1, 2, 3, 4, 5])

In [3]:
a2

array([ 6,  7,  8,  9, 10])

In [4]:
a1 + a2

array([ 7,  9, 11, 13, 15])

In [5]:
a2-a1

array([5, 5, 5, 5, 5])

In [6]:
a1 ** a2


array([      1,     128,    6561,  262144, 9765625])

## Broadcasting

In [7]:
l = [10,20,30,40]
arr = np.array(l)

In [8]:
arr + 10

array([20, 30, 40, 50])

In [9]:
arr2 = np.arange(1,26).reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [10]:
arr2 + 10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

## deep and shalow copy


In [11]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [16]:
slice = a[0:5]
slice = slice * 10
slice

array([10, 20, 30, 40, 50])

In [17]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [18]:
a[4:6] * 10

array([50, 60])

In [19]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [20]:
a
b = a

In [21]:
b[0] = 99
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

## matrix operations

In [22]:
mat1 = np.array([[1,2],[3,4]])
mat2 = np.array([[5,6],[7,8]])

In [23]:
mat1

array([[1, 2],
       [3, 4]])

In [24]:
mat2


array([[5, 6],
       [7, 8]])

In [25]:
mat1 @ mat2

array([[19, 22],
       [43, 50]])

In [26]:
mat1.transpose()

array([[1, 3],
       [2, 4]])

## Advance array manipulation

## Stacking array


In [27]:
mat1

array([[1, 2],
       [3, 4]])

In [28]:
mat2


array([[5, 6],
       [7, 8]])

In [29]:
np.vstack((mat1,mat2))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [30]:
np.hstack((mat1,mat2))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [32]:
np.column_stack((mat1,mat2))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

## Splitting array

In [33]:
c = np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [35]:
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [36]:
np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]