In [2]:
import numpy as np 

## 1. Numpy indexing and slicing of vectors

In [23]:
arr = np.arange(11,21)

In [24]:
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [25]:
arr[9]

20

In [26]:
arr[1:5]

array([12, 13, 14, 15])

In [28]:
arr_slice = arr[3::2]
arr_slice

array([14, 16, 18, 20])

In [29]:
arr_slice

array([14, 16, 18, 20])

## 2. Numpy Indexing and slicing of matrix

In [3]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [10]:
arr[5,4]

30

In [12]:
slice = arr[0:2,1:3]
slice

array([[2, 3],
       [7, 8]])

In [16]:
arr[3:6,3:6]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [17]:
arr[:,2]

array([ 3,  8, 13, 18, 23, 28])

## 3. Boolean Indexing

In [23]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [24]:
bool_index = arr % 2 == 0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [25]:
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])