# 1. Numpy Arrays

In [1]:
import numpy as np

## 2. Basic Array Creation

In [2]:
arr = np.array([1,2,3,4])

In [3]:
arr

array([1, 2, 3, 4])

In [5]:
a = [1,2,3.5,"hello"]
a

[1, 2, 3.5, 'hello']

In [6]:
np.array(a)

array(['1', '2', '3.5', 'hello'], dtype='<U32')

In [7]:
l = [[1,2,3],[4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## 3. Array generation Function

In [10]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
arr = np.zeros((6,6))
arr


array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [16]:
arr = np.ones((6,6))

In [17]:
arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [21]:
arr = np.linspace(1,5,3)
arr

array([1., 3., 5.])

## 4. Random generation function

In [23]:
np.random.rand(10)

array([0.60701905, 0.3801483 , 0.7084664 , 0.39060727, 0.14193305,
       0.02110771, 0.30183607, 0.80640004, 0.06071656, 0.89294265])

In [26]:
np.random.randn(10)

array([-0.51682488,  0.0864652 ,  0.08714068,  2.66142689, -0.30047474,
       -1.02142375,  0.75537636, -1.14723031,  0.78028094, -0.91831542])

In [29]:
np.random.randint(10,20,10)

array([14, 13, 11, 14, 15, 14, 15, 18, 10, 14])

## 5. Array Attributes

In [32]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
arr.shape

(3, 3)

In [34]:
arr.size

9

In [35]:
arr.dtype

dtype('int32')

In [36]:
arr.ndim


2

## 6. Array Methods

In [37]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [38]:
arr.min()

1

In [39]:
arr.max()

9

In [40]:
arr.sum()

45

In [42]:
np.sum(arr,axis = 1)

array([ 6, 15, 24])

In [43]:
arr.mean()

5.0

In [44]:
arr.std()

2.581988897471611

In [45]:
arr.argmax()

8

In [46]:
arr.argmin()

0

In [47]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [49]:
arr = arr.reshape((6,5))

In [50]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])